extends SceneTree
## Uses real wire responses generated by :studyCore:writeContractFixtures.

class FixtureBridge extends StudyTransport:
	var answers_sent: int = 0
	var timeouts_sent: int = 0
	var fail_answers: bool = false
	func is_available() -> bool:
		return true
	func exchange(type: String, _body: Dictionary = {}) -> Dictionary:
		if type == "timeout":
			timeouts_sent += 1
		if type == "answer":
			answers_sent += 1
			if fail_answers:
				return _error("연결 확인 테스트")
		if type == "end":
			return {"type": "summary", "body": {"correctCount": 0, "questionCount": 3, "answeredCount": 1}}
		if type == "begin":
			return JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/session.json"))
		var response: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/graded.json"))
		response["type"] = "reviewed" if type == "review" else "graded"
		response["body"]["selectedChoice"] = _body["selectedChoice"]
		response["body"]["timedOut"] = type == "timeout"
		response["body"]["correct"] = _body["selectedChoice"] == response["body"]["correctChoice"]
		response["body"]["reviewedCount"] = 1 if type == "review" and response["body"]["correct"] else 0
		return response

var failures: int = 0
var checks: int = 0

func _initialize() -> void:
	call_deferred("run")

func check(value: bool, message: String) -> void:
	checks += 1
	if not value:
		failures += 1
		push_error(message)
	else:
		print("PASS ", message)

func animate(game: JadeRunGame, seconds: float) -> void:
	for frame in int(ceil(seconds * 60)):
		game._physics_process(1.0 / 60)


func run() -> void:
	var fixture := FileAccess.get_file_as_string("res://tests/fixtures/session.json")
	var response := StudyTransport.decode_response(fixture, "fixture-begin")
	check(response.get("type") == "session", "decodes actual Kotlin session")
	check(StudyTransport.valid_session(response["body"]), "accepts generated three-question data")
	check(not fixture.contains("correctChoice"), "game receives no answer key")
	check(StudyTransport.decode_response(fixture, "stale")["type"] == "error", "rejects stale response")
	check(StudyTransport.decode_response("{", "id")["type"] == "error", "rejects malformed JSON")
	check(not StudyTransport.valid_session({"sessionId": "x", "questions": []}), "rejects empty question set")
	var game := load("res://scenes/main.tscn").instantiate() as JadeRunGame
	game.testing = true
	game.ignore_focus_pause = true
	root.add_child(game)
	game.set_physics_process(false)
	game.set_process(false)
	game.study.queue_free()
	var bridge := FixtureBridge.new()
	game.add_child(bridge)
	game.study = bridge
	await physics_frame
	await game.start_run()
	check(game.phase == JadeRunGame.Phase.APPROACH, "session approaches gate with a leap")
	animate(game, 1.3)
	check(game.study_session.size() > 0 and game.phase == JadeRunGame.Phase.QUESTION, "session starts at first question")
	check(game.player.position.y > 1.5 and game.player.visual.rotation.x < -1.0, "question holds a head-first dive in slow motion")
	var held_distance := game.distance
	var held_position := game.player.position
	game.perform_action("left")
	game._physics_process(2)
	check(game.distance == held_distance and game.player.animation.speed_scale > 0, "question preserves course progress while slow animation continues")
	check(game.player.position != held_position and game.hud.question_time_bar.value < 100, "micro movement and timer continue during question")
	var remaining_time := game._question_elapsed
	game.pause_run()
	animate(game, 3)
	check(game._question_elapsed == remaining_time, "pause freezes question timer")
	game.resume_run()
	check(game.phase == JadeRunGame.Phase.QUESTION and game._question_elapsed == remaining_time, "resume restores question without resetting time")
	var verdict: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/graded.json"))["body"]
	var right := int(verdict["correctChoice"])
	var wrong := (right + 1) % 3
	await game.submit_answer(wrong)
	check(game.phase == JadeRunGame.Phase.RESOLVE, "wrong answer starts collision before feedback")
	game.pause_run()
	var impact_distance := game.distance
	animate(game, 2)
	check(game.distance == impact_distance and game._cinema_elapsed == 0, "pause holds cinematic impact time")
	game.resume_run()
	check(game.phase == JadeRunGame.Phase.RESOLVE, "resume returns to pending collision")
	animate(game, 1.15)
	check(game.player.visual.rotation.x > 1.4, "wrong answer leaves character fallen")
	check(game.phase == JadeRunGame.Phase.FEEDBACK, "Kotlin verdict opens feedback")
	check(game.hud.study_feedback.is_visible_in_tree() and game.hud.study_feedback.text.contains(verdict["explanation"]), "Kotlin explanation is visible after collision")
	check(game.hud.study_continue.is_visible_in_tree() and not game.hud.hint.visible, "visible retry button replaces cinematic hint")
	await game.submit_answer(wrong)
	check(bridge.answers_sent == 1 and game.knowledge == 0, "double taps do not resubmit or reward")
	game.continue_after_question()
	animate(game, 1.3)
	check(game.question_index == 0 and game.phase == JadeRunGame.Phase.REVIEW, "wrong answer returns to guided review")
	await game.submit_answer(wrong)
	animate(game, 1.15)
	check(game.knowledge == 0 and not game._resolved, "wrong retry never opens gate")
	check(game.hud.study_feedback.is_visible_in_tree(), "wrong retry reopens explanation")
	game.continue_after_question()
	animate(game, 1.3)
	await game.submit_answer(right)
	check(game.phase == JadeRunGame.Phase.RESOLVE, "correct answer immediately starts gate breakthrough")
	check(not game.gate.broken, "correct verdict keeps wall closed until body contact")
	animate(game, .22)
	check(game.gate.broken, "body contact shatters the wall")
	animate(game, .93)
	check(game.phase == JadeRunGame.Phase.REWARD and not game.hud.study_panel.visible, "correct passage automatically continues without a feedback button")
	check(game.player.position.y < .1 and game.player.visual.rotation.x == 0, "correct passage ends with landing")
	check(game.knowledge == 5 and game.cleared == 1 and game.correct_count == 0, "review rewards learning without rewriting first score")
	await game.submit_answer(right)
	check(game.knowledge == 5, "resolved gate rewards only once")
	game.continue_after_question()
	check(game.phase == JadeRunGame.Phase.REWARD, "solved question unlocks automatic journey")
	game._physics_process(1)
	check(game.distance > 0 and game.question_index == 0, "reward movement precedes next question")
	game.pause_run()
	var paused_distance := game.distance
	game._physics_process(2)
	check(game.distance == paused_distance, "pause freezes reward movement")
	game.resume_run()
	check(game.phase == JadeRunGame.Phase.REWARD, "resume preserves reward phase")
	var prepared_gate := game._upcoming_gate
	var travelled := game.distance
	for frame in 151:
		game._physics_process(1.0 / 60)
	check(game.phase == JadeRunGame.Phase.QUESTION and game.question_index == 1, "short journey ends at next question")
	check(game.gate == prepared_gate and game.gate.number == 2, "next gate was already present in the world")
	check(game.distance > travelled, "gate transition preserves forward travel")
	await game.go_home()
	check(game.study_session.is_empty() and game.phase == JadeRunGame.Phase.READY, "home closes learning session")
	await game.start_run()
	check(game.phase == JadeRunGame.Phase.APPROACH, "session approaches gate with a leap")
	animate(game, 1.3)
	bridge.fail_answers = true
	await game.submit_answer(0)
	check(game.phase == JadeRunGame.Phase.STUDY_ERROR, "connection failure never invents a grade")
	check(game.player.animation.speed_scale == 0, "connection error keeps gameplay frozen")
	await game.go_home()
	bridge.fail_answers = false
	await game.start_run()
	animate(game, 1.3)
	animate(game, 16.2)
	check(bridge.timeouts_sent == 1 and game.phase == JadeRunGame.Phase.FEEDBACK, "timer expires once and reaches collision explanation")
	check(game.hud.study_feedback.text.contains("미응답") and game.knowledge == 0, "timeout never pretends a choice or awards energy")
	check(game.hud.study_feedback.is_visible_in_tree(), "timeout explanation is visible after collision")
	await game.go_home()
	game.queue_free()
	await process_frame
	print("STUDY RESULT %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)
